name: Unit Test
on:
  push:
    branches:
      - master
    paths:
      - src/*
      - include/*
      - test/*
jobs:
  test-pyctree-module:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.py}}
          architecture: x64
      - name: Create virtual env
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python --version
          gcc --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel pytest
      - name: Build and install extension
        run: |
          python ./setup.py install
      - name: Run tests
        run: |
          pytest -v
