name: Update Docs
on:
  push:
    branches:
      - master
    paths:
      - docs/*
      - mkdocs.yml
      - README.md
jobs:
  deploy-ghp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Setup virtual env
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python --version
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r ./requirements-docs.txt
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "Andrea Mecchia"
          git config --global user.email "andrea.mecchia@mail.polimi.it"
          mkdocs gh-deploy -f ./mkdocs.yml -b docs --force
